--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/poggit-orphanage/EconomyS
branches:
- master
projects:
  EconomySell:
    path: EconomySell/
    logo: EconomyAPI/icon.png
  EconomyShop:
    path: EconomyShop/
    logo: EconomyAPI/icon.png
...
